version: '3.0'

services:
    webserver:
        image: 'nginx:alpine'
        container_name: 'nginx'
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - 8080:80

    php-fpm:
        build: docker/php-fpm
        container_name: 'car-rentall-app'
        working_dir: /var/www/html
        volumes:
            - '.:/var/www/html'
            - '/docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'

    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./portainer-data:/data
        ports:
            - 9000:9000
    mysql:
        image: 'mysql:5.7'
        container_name: 'mysql'
        working_dir: /var/www/html
        restart: always
        volumes:
            - '.:/var/www/html'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=carRentall
            - MYSQL_USER=rootRentall
            - MYSQL_PASSWORD=rentall
        ports:
            - '3306:3306'
    
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: 'phpMyAdmin'
        restart: always
        ports:
            - 8082:80
        environment:
            - PMA_ARBITRARY=1